# Generated by Django 4.0.3 on 2022-06-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_post_image_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(auto_created=True, default='2022-06-02 10:11', verbose_name='Дата \\ Время публикации'),
            preserve_default=False,
        ),
    ]
