# Generated by Django 4.0.3 on 2022-06-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_comment_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата \\ Время публикации'),
        ),
    ]
