# Generated by Django 4.0.3 on 2022-06-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
