# Generated by Django 4.0.3 on 2022-06-05 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.day'),
            preserve_default=False,
        ),
    ]
