# Generated by Django 4.0.3 on 2022-06-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_time',
        ),
    ]
