# Generated by Django 4.0.3 on 2022-06-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_activity_end_time_activity_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='trainer',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
