# Generated by Django 4.0.3 on 2022-06-06 18:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, verbose_name='Дата \\ Время создания')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('image_preview', models.ImageField(upload_to='lesson_previews/%Y/%m/%d')),
                ('description', models.TextField(max_length=125, verbose_name='Описание')),
                ('slug', models.SlugField(verbose_name='Slug-ссылка')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Описание')),
                ('video', models.FileField(null=True, upload_to='lesson_videos/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Видеоматериал')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
