# Generated by Django 4.0.3 on 2022-06-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Платный'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image_preview',
            field=models.ImageField(upload_to='courses_previews/%Y/%m/%d', verbose_name='Превью курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image_preview',
            field=models.ImageField(null=True, upload_to='lesson_previews/%Y/%m/%d', verbose_name='Видео превью'),
        ),
    ]
